### ISSUE TITLE
What happens if an error is thrown?

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/ex-tackle#10]
Tackle currently handles exceptions pretty well, but what happens if an `error` is thrown?

At least, we should add some tests.

**Comment by predrag-rakic** [comment]
It goes through unhandled.
Had similar issue in Object Store Client.

**Comment by shiroyasha** [comment]
I know that part :)

To make it more precise, currently the rabbit message will not be sent to the delay/dead queue. 

Is this a good thing? Probably not, because a poisonous message can kill message consumtpion.

**Comment by predrag-rakic** [comment]
It will circumvent mechanism in place, yes.
It should be handled.

**Comment by predrag-rakic** [comment]
Just discovered that if exception is thrown, not only that message won't go to other queues, much worse, message won't be nack-ed until connection is closed - probably until process is restarted.

Reson: Tackle/Rabbit consumer start new message handling process for each  message received. If handler throws exception, only that particular process is terminated => connection remains open => no implicit nack.

**Comment by shiroyasha** [comment]
Resolved with https://github.com/renderedtext/ex-tackle/pull/14
