### ISSUE TITLE
Message is not acked/nacked

### ISSUE THREAD

**Issue by predrag-rakic** [renderedtext/ex-tackle#13]
This might or might not be ex-tackle issue.
It is possible that issue is in the message  handler (user code).

Root cause not known.
Detail description in this [post mortem](https://github.com/renderedtext/post-mortems/blob/master/2016-10-19-mailing-service-stopped-processing-rabbit-messagess.md).

It is known that Erlang processes(es) finished execution.
It is known that ack(s)/nack(s) did not reached RabbitMQ server.
Where and how did they got lost is not known.

I thought that Erlang processes are still alive somehow because Rabbit message handler has form:
```elixir
try do
  ...
rescue e ->
  exception_handler({:exception, e})
  raise e    
catch e ->
  exception_handler({:exception, e})
  throw e
end
```
But they are not.

**Comment by shiroyasha** [comment]
Resolved with https://github.com/renderedtext/ex-tackle/pull/14
