### ISSUE TITLE
Starting multiple consumers

### ISSUE THREAD

**Issue by teamon** [renderedtext/ex-tackle#17]
~~If I understand the tackle source code correctly, each incoming message gets it's own process. 
This can lead to spawning an unlimited number of processes. 
Do you plan to incorporate some limiting/pooling mechanism into tackle or is this out of scope?~~

**Comment by teamon** [comment]
Ah, I got that wrong, missed the `receive` block.
So, this goes the other way then - a single consumer is processing only one message at a time, and multiple consumers processes can't be started because of the conflicting `name: __MODULE__`. 

What is your approach to increasing the volume of processed messages, i.e. run more instances of consumer process?

**Comment by shiroyasha** [comment]
Our current approach is scale instances based on the number of messages in the queue. But yeah, it would be very nice if tackle could do the scaling in the app internally. 

Thanks for the suggestion. 🙇 

As a possible workaround, you can create multiple modules that listen on the the same queue, but this is definitely not an optimal solution.
