### ISSUE TITLE
connection pool

### ISSUE THREAD

**Issue by gottfrois** [renderedtext/ex-tackle#18]
Was reading through the code and was expecting to see poolboy somewhere to handle a connection pool. I'm curious to understand the reason you choose to go with tagged connections instead of a pool of connections?

**Comment by predrag-rakic** [comment]
Connections provide mechanism to cluster channels i.e. to map arbitrarily number of channels to any connection. We needed a way to be explicit about which channel goes through which connection. So we  named a connection.

Poolboy is (at least in my head) intended to handle pool of 'exactly the same' resources for which 'I don't care which one I'm going to grab i.e. use first available'.

**Comment by gottfrois** [comment]
> Poolboy is (at least in my head) intended to handle pool of 'exactly the same' resources for which 'I don't care which one I'm going to grab i.e. use first available'.

yes i think you are right

Thanks for the explanation, i'm working on a similar hex package but i was more concerned about not creating one connection for every channel, that's why i'm adding poolboy to the party.
