### ISSUE TITLE
Do not log rabbitmq url

### ISSUE THREAD

**Issue by arfl** [renderedtext/ex-tackle#21]
rabbitmq url often contain credentials. In tackle you log the rabbitmq url 3 times(i.e. [here](https://github.com/renderedtext/ex-tackle/blob/c5fb1323ab155eee3f253700c19df0c4fda85572/lib/tackle.ex#L22) ).We should not do it, because the credentials are in the logs now.

**Comment by radwo** [comment]
Resolved in https://github.com/renderedtext/ex-tackle/pull/46
